packages:
  - packages/*
  - packages/mui-envinfo/test
  - packages-internal/*
  - docs
  - test
  - test/moduleResolution
  - apps/*
  - bundle-size

patchedDependencies:
  styled-components: patches/styled-components.patch

onlyBuiltDependencies:
  - '@vvago/vale'
