name: Continuous releases

on:
  push:
    branches:
      - master
      - next
      - v*.x
  pull_request:

permissions: {}

jobs:
  continuous-releases:
    name: Continuous releases
    uses: mui/mui-public/.github/workflows/ci-base.yml@master
